# config/routes.yaml
api_login_check:
  path: /api/login


#Usuarios
api_user_create:
  path: /api/admin/userCreate
  controller: App\Controller\Usuarios\CrearUsuarioController
  methods: [ POST ]

api_user_list:
  path: /api/admin/userList
  controller: App\Controller\Usuarios\ListarUsuariosController
  methods: GET

api_user_edit:
  path: /api/admin/userUpdate/{id}
  controller: App\Controller\Usuarios\ActualizarUsuarioController
  methods: [ PUT ]

api_user_delete:
  path: /api/admin/userDelete/{id}
  controller: App\Controller\Usuarios\EliminarUsuarioController
  methods: [ DELETE ]

api_user_get:
  path: /api/admin/get/{id}
  controller: App\Controller\Usuarios\GetUsuarioController
  methods: [ GET ]

#Productos
api_producto_create:
  path: /api/producto/create
  controller: App\Controller\Producto\CrearProductoController
  methods: [ POST ]

api_producto_list:
    path: /api/producto/list
    controller: App\Controller\Producto\ListarProductoController
    methods: [ GET ]

api_producto_edit:
  path: /api/producto/edit/{id}
  controller: App\Controller\Producto\ActualizarProductoController
  methods: [ PUT ]

api_producto_delete:
    path: /api/producto/delete/{id}
    controller: App\Controller\Producto\EliminarProductoController
    methods: [ DELETE ]
#Ventas
api.ventas:
  path: /api/venta
  controller: App\Controller\Ventas\VentasController
  methods: [ POST ]

api.ventas.eliminar:
  path: /api/venta/eliminar/{id}
  controller: App\Controller\Ventas\EliminarVentasController
  methods: [ DELETE ]